import "./globals.css";

export const metadata = {
  title: "Tech Tree",
  description: "Welcome to Tech Tree!",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by head" />
      <body className="flex h-[100dvh] w-screen justify-center bg-slate-50">
        <div className="relative h-full w-full max-w-[28.125rem] px-[1.375rem] bg-[#FCFDFF] text-[#242424] font-normal text-base leading-[1.375rem] font-sans min-w-[28.125rem]">
          {children}
        </div>
      </body>
    </html>
  );
}
