"use client";
import "@utils/entrypoints.js";
import Head from "next/head";
import { useState } from "react";
import { chain } from "@utils/chat";
import { promptHelper } from "@utils/prompt";

export default function Home() {
  const [state, setState] = useState<string>("");
  const [botMessage, setBotMessage] = useState<string>("");

  const bufferMemoryChat = async () => {
    const res = await chain(promptHelper).call(
      {
        text: "나 배가 아파. 약 뭐먹어야 돼?",
      },
      [
        {
          handleLLMNewToken: async (token: any) =>
            setBotMessage((message) => message + token),
        },
      ]
    );
    console.log(res);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={() => {}}>
        <input
          onChange={(e) => {
            setState(e.target.value);
          }}
        />
        <button>Click to run a chain</button>
        <div>{botMessage}</div>
      </form>
      <button onClick={bufferMemoryChat}>click</button>
    </>
  );
}
