"use client";
import "../entrypoints.js";
import Head from "next/head";
import { useState } from "react";
import { chain } from "@/lib/chat";
import { promptInformation } from "@/lib/prompt";

const bufferMemoryChat = async () => {
  const res = await chain(promptInformation).call({ 약: "타이레놀" });
  console.log(res);
};
bufferMemoryChat();

export default function Home() {
  const [state, setState] = useState();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={() => {}}>
        <input
          onChange={(e) => {
            setState(e.target.value);
          }}
        />
        <button>Click to run a chain</button>
      </form>
    </>
  );
}
